export const examData = [
    {
        id: "mathematics",
        name: "Mathematics",
        color: "#3b82f6",
        icon: "∑",
        topics: [
            {
                id: "ratio-proportion",
                name: "Ratio & Proportion",
                icon: "📊",
                questionCount: 3,
                questions: [
                    {
                        id: "q1",
                        number: 1,
                        text: "A and B started a business by investing ₹84,000 and ₹80,000 respectively. After 4 months, B made an additional investment of ₹12,000. At the same time, C joined the business with investment of ₹96,000. What will be the ratio in the shares of profit of A, B and C in the profit made at the end of one year from starting the business?",
                        options: ["21 : 20 : 24", "21 : 23 : 24", "21 : 20 : 16", "21 : 22 : 16"],
                        correctAnswer: 3,
                        explanation: "A's capital: 84,000 × 12 = 1,008,000. B's capital: (80,000 × 4) + (92,000 × 8) = 1,056,000. C's capital: 96,000 × 8 = 768,000. Ratio = 1,008,000 : 1,056,000 : 768,000 = 21 : 22 : 16.",
                    },
                    {
                        id: "q2",
                        number: 2,
                        text: "If A : B = 2 : 3 and B : C = 4 : 5, find A : B : C.",
                        options: ["8 : 12 : 15", "2 : 3 : 4", "4 : 6 : 8", "6 : 9 : 12"],
                        correctAnswer: 0,
                        explanation: "A : B = 2 : 3 and B : C = 4 : 5. Multiply first ratio by 4 and second by 3. A : B : C = 8 : 12 : 15.",
                    },
                    {
                        id: "q3",
                        number: 3,
                        text: "The ratio of two numbers is 3 : 5 and their sum is 48. Find the larger number.",
                        options: ["18", "24", "30", "36"],
                        correctAnswer: 2,
                        explanation: "Let numbers be 3x and 5x. Sum = 8x = 48, so x = 6. Larger number = 5 × 6 = 30.",
                    },
                ],
            },
            {
                id: "algebra",
                name: "Algebra",
                icon: "𝑥",
                questionCount: 3,
                questions: [
                    {
                        id: "q4",
                        number: 1,
                        text: "Solve: 2x + 5 = 13",
                        options: ["2", "3", "4", "5"],
                        correctAnswer: 2,
                        explanation: "2x + 5 = 13 → 2x = 8 → x = 4",
                    },
                    {
                        id: "q5",
                        number: 2,
                        text: "Expand: (a + b)² = ?",
                        options: ["a² + 2ab + b²", "a² + ab + b²", "a² - 2ab + b²", "2a² + 2b²"],
                        correctAnswer: 0,
                        explanation: "(a + b)² = a² + 2ab + b²",
                    },
                    {
                        id: "q6",
                        number: 3,
                        text: "If x = 2, find the value of x³ + 3x² - 2x + 1",
                        options: ["13", "15", "17", "19"],
                        correctAnswer: 2,
                        explanation: "8 + 12 - 4 + 1 = 17",
                    },
                ],
            },
            {
                id: "geometry",
                name: "Geometry",
                icon: "△",
                questionCount: 2,
                questions: [
                    {
                        id: "q7",
                        number: 1,
                        text: "The sum of angles in a triangle is?",
                        options: ["90°", "180°", "270°", "360°"],
                        correctAnswer: 1,
                        explanation: "The sum of all interior angles in any triangle is always 180 degrees.",
                    },
                    {
                        id: "q8",
                        number: 2,
                        text: "What is the area of a circle with radius 7 cm? (Use π = 22/7)",
                        options: ["154 cm²", "176 cm²", "198 cm²", "220 cm²"],
                        correctAnswer: 0,
                        explanation: "Area = πr² = (22/7) × 49 = 154 cm²",
                    },
                ],
            },
        ],
    },
    {
        id: "science",
        name: "Science",
        color: "#22c55e",
        icon: "🔬",
        topics: [
            {
                id: "physics",
                name: "Physics",
                icon: "⚡",
                questionCount: 2,
                questions: [
                    {
                        id: "q9",
                        number: 1,
                        text: "What is the SI unit of force?",
                        options: ["Dyne", "Newton", "Joule", "Watt"],
                        correctAnswer: 1,
                        explanation: "The SI unit of force is Newton (N).",
                    },
                    {
                        id: "q10",
                        number: 2,
                        text: "What is the formula for kinetic energy?",
                        options: ["KE = mgh", "KE = ½mv²", "KE = mg", "KE = mv"],
                        correctAnswer: 1,
                        explanation: "KE = ½ × mass × velocity²",
                    },
                ],
            },
            {
                id: "chemistry",
                name: "Chemistry",
                icon: "⚗️",
                questionCount: 2,
                questions: [
                    {
                        id: "q11",
                        number: 1,
                        text: "What is the chemical formula for salt?",
                        options: ["NaCl", "KCl", "CaCl2", "MgCl2"],
                        correctAnswer: 0,
                        explanation: "Salt is sodium chloride — NaCl.",
                    },
                    {
                        id: "q12",
                        number: 2,
                        text: "pH scale ranges from?",
                        options: ["0 to 10", "1 to 14", "0 to 14", "1 to 7"],
                        correctAnswer: 2,
                        explanation: "pH scale ranges from 0 to 14.",
                    },
                ],
            },
        ],
    },
    {
        id: "history",
        name: "History",
        color: "#f59e0b",
        icon: "📚",
        topics: [
            {
                id: "ancient-history",
                name: "Ancient History",
                icon: "🏛️",
                questionCount: 2,
                questions: [
                    {
                        id: "q13",
                        number: 1,
                        text: "Who was the first emperor of India?",
                        options: ["Ashoka", "Chandragupta Maurya", "Akbar", "Harsha"],
                        correctAnswer: 1,
                        explanation: "Chandragupta Maurya founded the Mauryan Empire.",
                    },
                    {
                        id: "q14",
                        number: 2,
                        text: "In which year did the Indus Valley Civilization flourish?",
                        options: ["3000 BC", "2500 BC", "1500 BC", "1000 BC"],
                        correctAnswer: 1,
                        explanation: "The Indus Valley Civilization flourished around 2500 BC.",
                    },
                ],
            },
        ],
    },
];